import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./nav/page";
import Footer from "./footer/page"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "MRP BRAND",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" lang= "ru" className="translated-ltr">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Nav/>
        {children }
        
         <Footer/>
      </body>
    </html>
  );
}

